### ISSUE TITLE
Refactor to avoid `utils({})`

### ISSUE THREAD

**Issue by pbelbin** [sparksuite/waterfall-cli#112]
There are a number of cases, 3 in non-test, and 15 in tests, where the `utils({})` happens.

It appears that this is being done to gain access to util functions, the typical case being to use a function that does not have any dependency on the object values.

eg: processArguments, prettyPrintError, convertDashesToCamelCase, and the 'files' function group, which includes: isDirectory, isFile, getFiles, getDirectories functions.

This is a problem, because, for the internal functions that *do* require a valid settings object,     we really want to be able to tell TypeScript about this, let TypeScript help, and avoid having to check all the time for contents of the settings object being defined.

Perhaps it would make sense to break the functions that do not require the settings object properly defined into a different organizational unit than those that do.

We could also go a step further, and use TypeScript's class, and have these true utility functions declared as static, while the others could be available only as methods of a properly created object instance.  Some experimentation would be needed on this, to try and minimize the impact to clients.

A 'best' approach needs to be settled upon.

**Comment by pbelbin** [comment]
Here is the list of instances where the utils({}) happens:

<img width="500" alt="Image 2019-10-07 at 1 09 15 PM" src="https://user-images.githubusercontent.com/10079005/66336951-c32a1700-e903-11e9-8a10-2fd73ac3bb74.png">

**Comment by WesCossick** [comment]
I think the best solution would be to:

1. Move the `processArguments(argv)` function from the `utils.ts` file to a `process-arguments.ts` file. That way, `default-settings.ts` can simply import that single function without having to call `utils()` with current settings.
2. Move the `printPrettyError(message)` function from the `utils.ts` file to an `error-handling.ts` file. Then, we can import that from `waterfall-cli.ts` and also export that from the `index.ts` file.
3. Finally, all the remaining calls in `utils.test.js` can be updated to provide mock settings that meet the TypeScript requirements instead of trying to pass an empty object.
